### ISSUE TITLE
TextShow for Aeson KeyMap

### ISSUE THREAD

**Issue by flip111** [RyanGlScott/text-show-instances#17]
Could a textshow instance for this type be added ? https://hackage.haskell.org/package/aeson-2.2.0.0/docs/Data-Aeson-KeyMap.html

It's used to make up the json `Object` type https://hackage.haskell.org/package/aeson-2.2.0.0/docs/Data-Aeson.html#t:Object

**Comment by RyanGlScott** [comment]
Yes, certainly. Would you like to submit a patch for this?

**Comment by flip111** [comment]
I can try it. I think it would be best to start with a new module `TextShow.Data.Map` because `KeyMap` uses `Map`. Get this done first in one patch and when it's ok then to do a second patch for `KeyMap` in `TextShow.Data.Aeson`.

`TextShow.Data.Map` should probably go in `text-show` instead of this library.

What do you think?

**Comment by RyanGlScott** [comment]
Do note that there are `Map` instances already in [`TextShow.Data.Containers`](https://hackage.haskell.org/package/text-show-instances-3.9.5/docs/TextShow-Data-Containers.html).

**Comment by RyanGlScott** [comment]
Implemented in #18.
